name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Instalar dependências
        run: ./mvnw install -DskipTests

      - name: Executar testes em Gherkin
        run: ./mvnw test -Dcucumber.features="src\test\resources\features"
