CREATE SEQUENCE SEQ_TRAFFIC_LIGHT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_TRAFFIC_LIGHTS(
    ID_TRAFFIC_LIGHT INTEGER DEFAULT SEQ_TRAFFIC_LIGHT.NEXTVAL NOT NULL,
    LATITUDE FLOAT(126) NOT NULL,
    LONGITUDE FLOAT(126) NOT NULL,
    CURRENT_COLOR VARCHAR2(100) DEFAULT 'RED',
    LIGHT_TIMER INTEGER DEFAULT 0,
    TRAFFIC_DENSITY INTEGER DEFAULT 0,
    WEATHER_CONDITION VARCHAR2(100) DEFAULT 'SUNNY',
    PEDESTRIAN_MODE NUMBER(1) DEFAULT 0 CHECK (PEDESTRIAN_MODE IN (0, 1)),
    EMERGENCY_MODE NUMBER(1) DEFAULT 0 CHECK (EMERGENCY_MODE IN (0, 1)),
    FAULT_STATUS NUMBER(1) DEFAULT 0 CHECK (FAULT_STATUS IN (0, 1)),
    CURRENT_STATUS NUMBER(1) DEFAULT 0 CHECK (CURRENT_STATUS IN (0, 1))
);