CREATE SEQUENCE SEQ_TRAFFIC_SENSOR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_TRAFFIC_SENSORS(
    ID_TRAFFIC_SENSOR INTEGER DEFAULT SEQ_TRAFFIC_SENSOR.NEXTVAL NOT NULL,
    LATITUDE FLOAT(126) NOT NULL,
    LONGITUDE FLOAT(126) NOT NULL,
    TRAFFIC_DENSITY INTEGER DEFAULT 0,
    FAULT_STATUS NUMBER(1) DEFAULT 0 CHECK (FAULT_STATUS IN (0, 1)),
    CURRENT_STATUS NUMBER(1) DEFAULT 0 CHECK (CURRENT_STATUS IN (0, 1))
);