name: Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Ajuste para a versão Java do seu projeto

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn -f trafficManagement/pom.xml clean install -DskipTests

      - name: Run Cucumber Tests for trafficlight.feature
        run: mvn -f trafficManagement/pom.xml test -Dcucumber.features="$(pwd)/trafficManagement/src/test/resources/TrafficLightAPIs.feature" -e -X -Dcucumber.options="--plugin json:trafficManagement/target/cucumber-reports/Cucumber.json"
        env:
          CI: true

      # Diagnóstico: listar arquivos na pasta target para confirmar saída de testes
      - name: List Target Directory
        run: ls -R trafficManagement/target

      # Salvar o relatório como artefato do GitHub Actions
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: trafficManagement/target/cucumber-reports/Cucumber.json
